# Use the official Python image as a base image
FROM python:3.12-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .


# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Create a non-root user and set ownership of the /app directory
RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN chown -R trainee:mercari /app

# Switch to the non-root user
USER trainee

# Optional: Run Go-related commands if Go is also needed
# RUN go version

# Your additional Dockerfile instructions go here